// <auto-generated />
using System;
using Maliev.LifecycleService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Maliev.LifecycleService.Infrastructure.Migrations
{
    [DbContext(typeof(LifecycleDbContext))]
    [Migration("20260106142620_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Maliev.LifecycleService.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<string>("AfterState")
                        .HasColumnType("jsonb")
                        .HasColumnName("after_state");

                    b.Property<string>("BeforeState")
                        .HasColumnType("jsonb")
                        .HasColumnName("before_state");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("entity_type");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("EntityId");

                    b.HasIndex("Timestamp");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Maliev.LifecycleService.Domain.Entities.ExitInterview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ConductedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("conducted_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("FeedbackOnCompany")
                        .HasColumnType("text")
                        .HasColumnName("feedback_on_company");

                    b.Property<string>("FeedbackOnManager")
                        .HasColumnType("text")
                        .HasColumnName("feedback_on_manager");

                    b.Property<string>("FeedbackOnTeam")
                        .HasColumnType("text")
                        .HasColumnName("feedback_on_team");

                    b.Property<string>("ImprovementSuggestions")
                        .HasColumnType("text")
                        .HasColumnName("improvement_suggestions");

                    b.Property<DateTime>("InterviewDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("interview_date");

                    b.Property<Guid>("OffboardingChecklistId")
                        .HasColumnType("uuid")
                        .HasColumnName("offboarding_checklist_id");

                    b.Property<string>("ReasonForLeaving")
                        .HasColumnType("text")
                        .HasColumnName("reason_for_leaving");

                    b.Property<bool>("WouldRecommendCompany")
                        .HasColumnType("boolean")
                        .HasColumnName("would_recommend_company");

                    b.HasKey("Id")
                        .HasName("pk_exit_interviews");

                    b.HasIndex("OffboardingChecklistId")
                        .IsUnique()
                        .HasDatabaseName("ix_exit_interviews_offboarding_checklist_id");

                    b.ToTable("exit_interviews", (string)null);
                });

            modelBuilder.Entity("Maliev.LifecycleService.Domain.Entities.OffboardingChecklist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_date");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("EligibleForRehire")
                        .HasColumnType("boolean")
                        .HasColumnName("eligible_for_rehire");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<bool>("PaycheckReleaseBlocked")
                        .HasColumnType("boolean")
                        .HasColumnName("paycheck_release_blocked");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("TerminationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("termination_date");

                    b.Property<string>("TerminationReason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("termination_reason");

                    b.HasKey("Id")
                        .HasName("pk_offboarding_checklists");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("offboarding_checklists", (string)null);
                });

            modelBuilder.Entity("Maliev.LifecycleService.Domain.Entities.OffboardingTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AssignedTo")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<Guid?>("CompletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("completed_by");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_date");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<bool>("IsPaycheckBlocker")
                        .HasColumnType("boolean")
                        .HasColumnName("is_paycheck_blocker");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("OffboardingChecklistId")
                        .HasColumnType("uuid")
                        .HasColumnName("offboarding_checklist_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_offboarding_tasks");

                    b.HasIndex("OffboardingChecklistId")
                        .HasDatabaseName("ix_offboarding_tasks_offboarding_checklist_id");

                    b.ToTable("offboarding_tasks", (string)null);
                });

            modelBuilder.Entity("Maliev.LifecycleService.Domain.Entities.OnboardingChecklist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_date");

                    b.Property<int>("CompletedItems")
                        .HasColumnType("integer")
                        .HasColumnName("completed_items");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TotalItems")
                        .HasColumnType("integer")
                        .HasColumnName("total_items");

                    b.HasKey("Id")
                        .HasName("pk_onboarding_checklists");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("onboarding_checklists", (string)null);
                });

            modelBuilder.Entity("Maliev.LifecycleService.Domain.Entities.OnboardingItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AssignedTo")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<Guid?>("CompletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("completed_by");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_date");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<int>("DaysDue")
                        .HasColumnType("integer")
                        .HasColumnName("days_due");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("OnboardingChecklistId")
                        .HasColumnType("uuid")
                        .HasColumnName("onboarding_checklist_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_onboarding_items");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("OnboardingChecklistId")
                        .HasDatabaseName("ix_onboarding_items_onboarding_checklist_id");

                    b.ToTable("onboarding_items", (string)null);
                });

            modelBuilder.Entity("Maliev.LifecycleService.Domain.Entities.OnboardingTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_onboarding_templates");

                    b.HasIndex("DepartmentId");

                    b.ToTable("onboarding_templates", (string)null);
                });

            modelBuilder.Entity("Maliev.LifecycleService.Domain.Entities.OnboardingTemplateItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<int>("DaysDue")
                        .HasColumnType("integer")
                        .HasColumnName("days_due");

                    b.Property<string>("DefaultAssigneeRole")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("default_assignee_role");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_onboarding_template_items");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("ix_onboarding_template_items_template_id");

                    b.ToTable("onboarding_template_items", (string)null);
                });

            modelBuilder.Entity("Maliev.LifecycleService.Domain.Entities.ExitInterview", b =>
                {
                    b.HasOne("Maliev.LifecycleService.Domain.Entities.OffboardingChecklist", "OffboardingChecklist")
                        .WithOne()
                        .HasForeignKey("Maliev.LifecycleService.Domain.Entities.ExitInterview", "OffboardingChecklistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exit_interviews__offboarding_checklists_offboarding_checklist~");

                    b.Navigation("OffboardingChecklist");
                });

            modelBuilder.Entity("Maliev.LifecycleService.Domain.Entities.OffboardingTask", b =>
                {
                    b.HasOne("Maliev.LifecycleService.Domain.Entities.OffboardingChecklist", "Checklist")
                        .WithMany("Tasks")
                        .HasForeignKey("OffboardingChecklistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_offboarding_tasks_offboarding_checklists_offboarding_checkl~");

                    b.Navigation("Checklist");
                });

            modelBuilder.Entity("Maliev.LifecycleService.Domain.Entities.OnboardingItem", b =>
                {
                    b.HasOne("Maliev.LifecycleService.Domain.Entities.OnboardingChecklist", "Checklist")
                        .WithMany("Items")
                        .HasForeignKey("OnboardingChecklistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_onboarding_items_onboarding_checklists_onboarding_checklist~");

                    b.Navigation("Checklist");
                });

            modelBuilder.Entity("Maliev.LifecycleService.Domain.Entities.OnboardingTemplateItem", b =>
                {
                    b.HasOne("Maliev.LifecycleService.Domain.Entities.OnboardingTemplate", "Template")
                        .WithMany("Items")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_onboarding_template_items_onboarding_templates_template_id");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Maliev.LifecycleService.Domain.Entities.OffboardingChecklist", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Maliev.LifecycleService.Domain.Entities.OnboardingChecklist", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Maliev.LifecycleService.Domain.Entities.OnboardingTemplate", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
